# Generated by Django 6.0.3 on 2026-03-13 06:23

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('text', models.TextField()),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '仮説',
                'verbose_name_plural': '仮説',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('source_title', models.CharField(blank=True, max_length=500)),
                ('stance', models.CharField(choices=[('support', '支持'), ('counter', '反証')], max_length=10)),
                ('confidence', models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], default='medium', max_length=10)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='causal.hypothesis')),
            ],
            options={
                'verbose_name': '証拠',
                'verbose_name_plural': '証拠',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('complexity_score', models.FloatField(blank=True, null=True)),
                ('selected_model', models.CharField(default='sonnet', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待機中'), ('running', '実行中'), ('completed', '完了'), ('error', 'エラー')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'セッション',
                'verbose_name_plural': 'セッション',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='causal.session'),
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50)),
                ('node_type', models.CharField(choices=[('question', '質問'), ('hypothesis', '仮説'), ('support', '支持'), ('counter', '反証'), ('concept', '概念')], max_length=20)),
                ('label', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='causal.session')),
            ],
            options={
                'verbose_name': 'グラフノード',
                'verbose_name_plural': 'グラフノード',
                'unique_together': {('session', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('causal', '因果'), ('support', '支持'), ('counter', '反証'), ('rel', '関連')], max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='causal.graphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='causal.graphnode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='causal.session')),
            ],
            options={
                'verbose_name': 'グラフエッジ',
                'verbose_name_plural': 'グラフエッジ',
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('node_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to='causal.session')),
            ],
            options={
                'verbose_name': 'トークン使用量',
                'verbose_name_plural': 'トークン使用量',
                'ordering': ['-created_at'],
            },
        ),
    ]
