# Generated by Django 6.0.3 on 2026-03-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='source_url',
            field=models.TextField(blank=True),
        ),
    ]
