# Generated by Django 6.0.3 on 2026-03-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causal', '0002_evidence_source_url_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='final_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='references',
            field=models.JSONField(default=list),
        ),
    ]
