# Generated by Django 6.0.3 on 2026-03-13 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('default_model', models.CharField(choices=[('auto', '自動判定'), ('sonnet', 'Sonnet'), ('opus', 'Opus')], default='auto', max_length=20)),
                ('complexity_threshold', models.IntegerField(default=3)),
                ('system_prompt', models.TextField(blank=True)),
                ('color_mode', models.CharField(choices=[('dark', 'ダーク'), ('light', 'ライト'), ('system', 'システム')], default='dark', max_length=10)),
                ('graph_animation', models.BooleanField(default=True)),
                ('graph_grid', models.BooleanField(default=True)),
                ('animation_speed', models.CharField(choices=[('slow', '低速'), ('normal', '標準'), ('fast', '高速')], default='normal', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー設定',
                'verbose_name_plural': 'ユーザー設定',
            },
        ),
    ]
