# Generated by Django 6.0.3 on 2026-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('ja', '日本語'), ('en', 'English')], default='ja', max_length=5),
        ),
    ]
