# Generated by Django 6.0.3 on 2026-03-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_language_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='brave_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
